/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_hsae_audiorecorder_AACEncode */
/*
 * Class:     com_hsae_audiorecorder_AACEncoder
 * Signature: ()V
 */


/*CopyRight  hsae yangzhou RD dep.
*audthor turkeyzhu<turkeyzhu@gmail.com>
*create 201406
*/
 
#include <jni.h>
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "voAAC.h"
#include <unistd.h>

#include "cmnMemory.h"




#ifdef __cplusplus
extern "C" {
#endif


#define  VO_AAC_E_OUTPUT	  1
//#define READ_SIZE	((int)(7200+1280*2.5))
#define READ_SIZE 1024*8
unsigned char outBuf[1024*8];
//unsigned char inBuf[1024*8];
unsigned char inBuf[1280*8];



typedef int (VO_API * VOGETAUDIODECAPI) (VO_AUDIO_CODECAPI * pDecHandle);




JNIEXPORT jint JNICALL Java_com_hsae_audiorecorder_AACEncoder_init(
		JNIEnv *env, jclass cls, jint inSamplerate, jint outChannel,
		jint outSamplerate, jint outBitrate, jint quality) ;


JNIEXPORT jsize JNICALL Java_com_hsae_audiorecorder_AACEncoder_encode(
		JNIEnv *env, jclass cls,jshortArray pcm_buf,jsize pcm_size, jbyteArray aac_buf) ;

JNIEXPORT jint JNICALL Java_com_hsae_audiorecorder_AACEncoder_uninit();


#ifdef __cplusplus
}
#endif
